App.EndPoint.Mvc.UI/Models/CommentViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace App.EndPoint.Mvc.UI.Models
{
    public class CommentViewModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "وارد کردن فیلد {0} الزامی است")]
        [Display(Name ="متخصص/سرویس")]
        public int ExpertServiceId { get; set; }

        [Display(Name ="متخصص")]
        public string? Expert { get; set; }

        [Display(Name ="سرویس")]
        public string? Service { get; set; }
        public int CustomerId { get; set; }

        [Display(Name ="مشتری")]
        public string? Customer { get; set; }

        [Required(ErrorMessage = "وارد کردن فیلد {0} الزامی است")]
        [Display(Name ="عنوان")]
        public string Title { get; set; }

        [Display(Name ="توضیحات")]
        public string? Text { get; set; }

        [Display(Name ="تعداد موافق")]
        public int LikeCount { get; set; } = 0;

        [Display(Name ="تعداد مخالف")]
        public int DislikeCount { get; set; } = 0;

        [Display(Name ="تایید شده")]
        public bool IsConfirmed { get; set; }
    }
}

App.EndPoint.Mvc.UI/Models/ExpertServiceViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace App.EndPoint.Mvc.UI.Models
{
    public class ExpertServiceViewModel
    {
        public int? Id { get; set; }

        [Required(ErrorMessage = "وارد کردن فیلد {0} الزامی است")]
        [Display(Name = "متخصص")]
        public int ExpertId { get; set; }

        [Display(Name = "متخصص")]
        public string? Expert { get; set; }

        [Required(ErrorMessage = "وارد کردن فیلد {0} الزامی است")]
        [Display(Name = "سرویس")]
        public int ServiceId { get; set; }

        [Display(Name = "سرویس")]
        public string? Service { get; set; }

        [Display(Name = "تاریخ ایجاد")]
        public DateTime? CreationDate { get; set; }

        [Display(Name = "تعداد کامنت")]
        public int? CommentsCount { get; set; }
    }
}

App.EndPoint.Mvc.UI/Areas/Admin/Controllers/CommentController.cs
using App.Domain.Core.Expert.Contracts.AppServices;
using App.EndPoint.Mvc.UI.Models;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace App.EndPoint.Mvc.UI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "admin")]
    public class CommentController : Controller
    {
        private readonly ICommentAppService _commentAppService;
        private readonly IMapper _mapper;
        private readonly ILogger<CommentController> _logger;

        public CommentController(ICommentAppService commentAppService,
            IMapper mapper,
            ILogger<CommentController> logger)
        {
            _commentAppService = commentAppService;
            _mapper = mapper;
            _logger = logger;
        }

        public async Task<IActionResult> Index(string? keyWord, bool? isConfirmed, CancellationToken cancellationToken)
        {
            var model = _mapper.Map<List<CommentViewModel>>(await _commentAppService.GetAll(keyWord, isConfirmed, cancellationToken));
            return View(model);
        }

        public async Task<IActionResult> ChangeConfirmState(int id, CancellationToken cancellationToken)
        {
            try
            {
                await _commentAppService.ChangeConfirmState(id, cancellationToken);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(String.Empty, ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id, CancellationToken cancellationToken)
        {
            try
            {
                await _commentAppService.Delete(id, cancellationToken);
                _logger.LogInformation("comment with id: {commentId} was deleted by {userRole}", id, "admin");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(String.Empty, ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

App.EndPoint.Mvc.UI/Controllers/ExpertController.cs
using App.Domain.Core.BaseData.Contracts.AppServices;
using App.Domain.Core.BaseData.Dtos;
using App.Domain.Core.Customer.Contracts.AppServices;
using App.Domain.Core.Expert.Contracts.AppServices;
using App.Domain.Core.Expert.Dtos;
using App.Domain.Core.Service.Contracts.AppServices;
using App.EndPoint.Mvc.UI.Models;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace App.EndPoint.Mvc.UI.Controllers
{
    public class ExpertController : Controller
    {
        private readonly ILogger<ExpertController> _logger;
        private readonly IUserAppService _userAppService;
        private readonly IExpertServiceAppService _expertServiceAppService;
        private readonly IServiceAppService _serviceAppService;
        private readonly IOrderAppService _orderAppService;
        private readonly ITenderAppService _tenderAppService;
        private readonly IPastWorkAppService _pastWorkAppService;
        private readonly IMapper _mapper;
        private readonly ICommentAppService _commentAppService;

        public ExpertController(ILogger<ExpertController> logger,
            IUserAppService userAppService,
            IExpertServiceAppService expertServiceAppService,
            IServiceAppService serviceAppService,
            IOrderAppService orderAppService,
            ITenderAppService tenderAppService,
            IPastWorkAppService pastWorkAppService,
            ICommentAppService commentAppService,
            IMapper mapper)
        {
            _logger = logger;
            _userAppService = userAppService;
            _expertServiceAppService = expertServiceAppService;
            _serviceAppService = serviceAppService;
            _orderAppService = orderAppService;
            _tenderAppService = tenderAppService;
            _pastWorkAppService = pastWorkAppService;
            _commentAppService = commentAppService;
            _mapper = mapper;
        }
        [Authorize(Roles = "expert")]
        public async Task<ActionResult> Index(CancellationToken cancellationToken)
        {
            int id = Convert.ToInt32(this.User.FindFirstValue(ClaimTypes.NameIdentifier));
            var model = _mapper.Map<UserDetailViewModel>(await _userAppService.Get(id, cancellationToken));
            return View(model);
        }

        public async Task<IActionResult> Edit(CancellationToken cancellationToken)
        {
            int id = Convert.ToInt32(this.User.FindFirstValue(ClaimTypes.NameIdentifier));
            var model = _mapper.Map<UserEditViewModel>(await _userAppService.Get(id, cancellationToken));
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UserEditViewModel model, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                var dto = _mapper.Map<AppUserDetailDto>(model);
                var result = await _userAppService.Update(dto, cancellationToken);
                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError(String.Empty, item.Description);
                    }
                    return View(model);
                }
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditPicture(IFormFile? userImage, CancellationToken cancellationToken)
        {
            if (userImage == null)
                return RedirectToAction(nameof(Index));
            if (!userImage.ContentType.Contains("image"))
                ModelState.AddModelError(string.Empty, "فرمت عکس صحیح نیست.");
            if (ModelState.IsValid)
            {
                int id = Convert.ToInt32(this.User.FindFirstValue(ClaimTypes.NameIdentifier));
                await _userAppService.UpdatePicture(id, userImage, cancellationToken);
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public async Task<ActionResult> ExpertService(CancellationToken cancellationToken)
        {
            int id = Convert.ToInt32(this.User.FindFirstValue(ClaimTypes.NameIdentifier));
            var model = new ExpertServiceEditViewModel();
            model.ExpertServices = _mapper.Map<List<ExpertServiceViewModel>>(await _expertServiceAppService.GetByExpertId(id, cancellationToken));
            model.Services = _mapper.Map<List<ServiceViewModel>>(await _serviceAppService.GetAll(null, cancellationToken))
                .Where(s => !model.ExpertServices.Any(es => es.ServiceId == s.Id)).ToList();
            foreach (var expertService in model.ExpertServices)
                expertService.CommentsCount = (await _commentAppService.GetByExpertServiceId((int)expertService.Id, null, cancellationToken)).Count;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddExpertService(int serviceId, CancellationToken cancellationToken)
        {
            int expertId = Convert.ToInt32(this.User.FindFirstValue(ClaimTypes.NameIdentifier));
            await _expertServiceAppService.Add(expertId, serviceId, cancellationToken);
            return RedirectToAction(nameof(ExpertService));
        }

        public async Task<ActionResult> DeleteExpertService(int id, CancellationToken cancellationToken)
        {
            await _expertServiceAppService.Delete(id, cancellationToken);
            return RedirectToAction(nameof(ExpertService));
        }

        public async Task<ActionResult> Orders(CancellationToken cancellationToken)
        {
            int id = Convert.ToInt32(this.User.FindFirstValue(ClaimTypes.NameIdentifier));
            var orders = _mapper.Map<List<OrderForExpertViewModel>>(await _orderAppService.GetByExpertId(id, cancellationToken));
            return View(orders);
        }

        public async Task<ActionResult> Tenders(CancellationToken cancellationToken)
        {
            int id = Convert.ToInt32(this.User.FindFirstValue(ClaimTypes.NameIdentifier));
            var model = _mapper.Map<List<TenderWithOrderViewModel>>(await _tenderAppService.GetTendersAndOrdersByExpertId(id, cancellationToken));
            return View(model);
        }

        public ActionResult AddTender(int id)
        {
            var tender = new TenderViewModel() { OrderId = id };
            return View(tender);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddTender(TenderViewModel model, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                model.ExpertId = Convert.ToInt32(this.User.FindFirstValue(ClaimTypes.NameIdentifier));
                await _tenderAppService.Add(_mapper.Map<TenderDto>(model), cancellationToken);
                return RedirectToAction(nameof(Orders));
            }
            return View();
        }

        public async Task<ActionResult> TenderDetail(int id, CancellationToken cancellationToken)
        {
            var tender = _mapper.Map<TenderViewModel>(await _tenderAppService.Get(id, cancellationToken));
            return View(tender);
        }

        public async Task<ActionResult> EditTender(int id, CancellationToken cancellationToken)
        {
            var tender = _mapper.Map<TenderViewModel>(await _tenderAppService.Get(id, cancellationToken));
            return View(tender);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditTender(TenderViewModel model, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                model.ExpertId = Convert.ToInt32(this.User.FindFirstValue(ClaimTypes.NameIdentifier));
                await _tenderAppService.Add(_mapper.Map<TenderDto>(model), cancellationToken);
                return RedirectToAction(nameof(Tenders));
            }
            return View();
        }

        public async Task<ActionResult> DeleteTender(int id, CancellationToken cancellationToken)
        {
            await _tenderAppService.Delete(id, cancellationToken);
            return RedirectToAction(nameof(Tenders));
        }
        public async Task<ActionResult> WorkDone(int id, CancellationToken cancellationToken)
        {
            await _orderAppService.Done(id, cancellationToken);
            return RedirectToAction(nameof(Tenders));
        }

        public async Task<IActionResult> PastWorks(CancellationToken cancellationToken)
        {
            int id = Convert.ToInt32(this.User.FindFirstValue(ClaimTypes.NameIdentifier));
            var model = _mapper.Map<List<PastWorkViewModel>>(await _pastWorkAppService.GetByExpertId(id, cancellationToken));
            return View(model);
        }

        public async Task<ActionResult> Comments(int id, string keyWord, CancellationToken cancellationToken)
        {
            var comments = _mapper.Map<List<CommentViewModel>>(await _commentAppService.GetByExpertServiceId(id, keyWord, cancellationToken));
            return View(comments);
        }
    }
}

App.EndPoint.Mvc.UI/Controllers/OrderController.cs
using App.Domain.Core.Customer.Contracts.AppServices;
using App.Domain.Core.Customer.Dtos;
using App.Domain.Core.Expert.Contracts.AppServices;
using App.Domain.Core.Service.Contracts.AppServices;
using App.EndPoint.Mvc.UI.Models;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace App.EndPoint.Mvc.UI.Controllers
{
    [Authorize(Roles = "customer")]
    public class OrderController : Controller
    {
        private readonly IOrderAppService _orderAppService;
        private readonly IOrderStateAppService _orderStateAppService;
        private readonly ITenderAppService _tenderAppService;
        private readonly IServiceAppService _serviceAppService;
        private readonly IMapper _mapper;

        public OrderController(IOrderAppService orderAppService,
            IOrderStateAppService orderStateAppService,
            ITenderAppService tenderAppService,
            IServiceAppService serviceAppService,
            IMapper mapper)
        {
            _orderAppService = orderAppService;
            _orderStateAppService = orderStateAppService;
            _tenderAppService = tenderAppService;
            _serviceAppService = serviceAppService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index(string keyWord, CancellationToken cancellationToken)
        {
            ViewBag.UserName = this.User.FindFirstValue(ClaimTypes.Name);
            int customerId = Convert.ToInt32(this.User.FindFirstValue(ClaimTypes.NameIdentifier));
            var model = _mapper.Map<List<OrderViewModel>>(await _orderAppService.GetByCustomerId(customerId, keyWord, cancellationToken));

            foreach (var item in model)
            {
                item.TendersCount = (await _tenderAppService.GetByOrder((int)item.Id, cancellationToken)).Count;
            }
            return View(model);
        }

        public async Task<IActionResult> Create(int id, CancellationToken cancellationToken)
        {
            var customerId = Convert.ToInt32(this.User.FindFirstValue(ClaimTypes.NameIdentifier));
            OrderDto dto = new()
            {
                CustomerId = customerId,
                ServiceId = id,
            };
            var orderId = await _orderAppService.Add(dto, cancellationToken);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Tenders(int id, CancellationToken cancellationToken)
        {
            var customerId = Convert.ToInt32(this.User.FindFirstValue(ClaimTypes.NameIdentifier));
            OrderTenderViewModel model = new();
            model.Order = _mapper.Map<OrderViewModel>(await _orderAppService.Get(id, customerId, cancellationToken));
            model.Tenders = _mapper.Map<List<TenderViewModel>>(await _tenderAppService.GetByOrder(id, cancellationToken));
            model.Order.TendersCount = model.Tenders.Count;
            return View(model);
        }

        public async Task<IActionResult> AcceptTender(int id, CancellationToken cancellationToken)
        {
            var dto = await _tenderAppService.Accept(id, cancellationToken);
            return RedirectToAction(nameof(Tenders), new { id = dto.OrderId });
        }

        public async Task<IActionResult> CancelTender(int id, CancellationToken cancellationToken)
        {
            var dto = await _tenderAppService.Cancel(id, cancellationToken);
            return RedirectToAction(nameof(Tenders), new { id = dto.OrderId });
        }

        public async Task<IActionResult> Delete(int id, CancellationToken cancellationToken)
        {
            var customerId = Convert.ToInt32(this.User.FindFirstValue(ClaimTypes.NameIdentifier));
            try
            {
                await _orderAppService.Delete(id, customerId, cancellationToken);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

App.EndPoint.Mvc.UI/Views/Expert/AddTender.cshtml
@model TenderViewModel

@{
    ViewData["Title"] = "ایجاد پیشنهاد";
}
<div class="col-12 row">
    <div class="card-body p-0 ">
        <!-- Nested Row within Card Body -->
        <div class="row flex-row justify-content-center">
            <div class="col-lg-8">
                <div class="p-5">
                    <div class="text-center">
                        <h1 class="h4 text-gray-900 mb-4">ایجاد پیشنهاد</h1>
                    </div>
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <form class="user" asp-action="AddTender" method="post">
                        <input hidden asp-for=OrderId value=@Model.OrderId />
                        <div class="form-group row">
                            <div class="col-sm-6 mb-3 mb-sm-0">
                                <input type="number" class="form-control form-control-user input" asp-for="Price" placeholder=" ">
                                <div class="cut"></div>
                                <label asp-for=Price class="placeholder"></label>
                                <span asp-validation-for=Price class="text-danger"></span>
                            </div>
                            <div class="col-sm-6">
                                <input type="datetime-local" class="form-control form-control-user input" asp-for="StartDate" placeholder=" ">
                                <div class="cut"></div>
                                <label asp-for=StartDate class="placeholder"></label>
                                <span asp-validation-for=StartDate class="text-danger"></span>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-6 mb-3 mb-sm-0">
                                <input type="time" class="form-control form-control-user input" asp-for="RequiredTime" placeholder=" ">
                                <div class="cut cut-long"></div>
                                <label asp-for=RequiredTime class="placeholder"></label>
                                <span asp-validation-for=RequiredTime class="text-danger"></span>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="container col-sm-6">
                                <button type="submit" class="btn btn-primary btn-user btn-block mb-3 mb-sm-0">
                                    ایجاد پیشنهاد
                                </button>
                                <a class="btn btn-danger btn-user btn-block" asp-action="Orders">انصراف</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

App.EndPoint.Mvc.UI/Views/Expert/Comments.cshtml
@model IEnumerable<CommentViewModel>

@{
    string faName = "نظر";
    string enName = "Comment";
    ViewData["Title"] = $"لیست {faName}ات";
    int rowCount = 1;
}

<div class="d-flex justify-content-between">
    <h3>لیست @(faName)‌ات</h3>
    <form class="col-4" method="get" asp-controller="Expert" asp-action="Comments">
        <div class="input-group">
            @*<input hidden name="id" value=@ViewBag.ExpertServiceId />*@
            <input type="search" class="form-control rounded" placeholder="کلید واژه..." name="keyWord" />
            <button type="submit" class="btn btn-outline-primary">جستجو</button>
            <a class="btn btn-primary" asp-controller="Expert" asp-action="Comments">نمایش همه</a>
        </div>
    </form>
</div>
<hr>

<table class="table table-striped table-hover text-center">
    <thead>
        <tr>
            <th scope="col">
                #
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Service)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.Customer)
            </th>
            <th scope="col"  class="col-2">
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th scope="col" class="col-5">
                @Html.DisplayNameFor(model => model.Text)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.LikeCount)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model => model.DislikeCount)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td scope="row">
                    @(rowCount++)
                </td>
                <td>@item.Service</td>
                <td>@item.Customer</td>
                <td>@item.Title</td>
                <td>@item.Text</td>
                <td>@item.LikeCount</td>
                <td>@item.DislikeCount</td>
            </tr>
        }
    </tbody>
</table>

App.EndPoint.Mvc.UI/Views/Expert/EditTender.cshtml
@model TenderViewModel

@{
    ViewData["Title"] = "ویرایش پیشنهاد";
}
<div class="col-12 row">
    <div class="card-body p-0 ">
        <!-- Nested Row within Card Body -->
        <div class="row flex-row justify-content-center">
            <div class="col-lg-8">
                <div class="p-5">
                    <div class="text-center">
                        <h1 class="h4 text-gray-900 mb-4">ویرایش پیشنهاد</h1>
                    </div>
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <form class="user" asp-action="AddTender" method="post">
                        <input hidden asp-for=OrderId value=@Model.OrderId />
                        <div class="form-group row">
                            <div class="col-sm-6 mb-3 mb-sm-0">
                                <input type="number" class="form-control form-control-user input" asp-for="Price" placeholder=" ">
                                <div class="cut"></div>
                                <label asp-for=Price class="placeholder"></label>
                                <span asp-validation-for=Price class="text-danger"></span>
                            </div>
                            <div class="col-sm-6">
                                <input type="datetime-local" class="form-control form-control-user input" asp-for="StartDate" placeholder=" ">
                                <div class="cut"></div>
                                <label asp-for=StartDate class="placeholder"></label>
                                <span asp-validation-for=StartDate class="text-danger"></span>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-sm-6 mb-3 mb-sm-0">
                                <input type="time" class="form-control form-control-user input" asp-for="RequiredTime" placeholder=" ">
                                <div class="cut cut-long"></div>
                                <label asp-for=RequiredTime class="placeholder"></label>
                                <span asp-validation-for=RequiredTime class="text-danger"></span>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="container col-sm-6">
                                <button type="submit" class="btn btn-primary btn-user btn-block mb-3 mb-sm-0">
                                    ویرایش پیشنهاد
                                </button>
                                <a class="btn btn-danger btn-user btn-block" asp-action="Tenders">انصراف</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

App.EndPoint.Mvc.UI/Views/Expert/ExpertService.cshtml
@model ExpertServiceEditViewModel

@{
    string faName = "تخصص";
    string enName = "ExpertService";
    ViewData["Title"] = $"لیست {faName}‌ها";
    int rowCount = 1;
}
<div class="d-flex justify-content-between">
    <h3>لیست @(faName)‌ها</h3>
    <div>
        <a id="add" class="btn btn-success" data-toggle="modal" data-target="#addModal">
            جدید
        </a>
    </div>
</div>
<hr>
<!-- Modal -->
<div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="addModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addModalLabel">افزودن تخصص</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <form class="user" asp-action="AddExpertService" method="post">
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="formFile" class="form-label">تخصص</label>
                        <select name="serviceId" class="selectpicker form-control form-control-user" data-live-search="true"
                                asp-items=@(new SelectList(Model.Services,"Id","Name"))>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">
                        انصراف
                    </button>
                    <button type="submit" class="btn btn-success">
                        تایید
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<table class="table table-striped table-hover text-center">
    <thead>
        <tr>
            <th scope="col">
                #
            </th>
            <th scope="col">
                @Html.DisplayNameForInnerType((ExpertServiceViewModel e)=>e.Service)
            </th>
            <th scope="col">
                @Html.DisplayNameForInnerType((ExpertServiceViewModel e)=>e.CreationDate)
            </th>
            <th scope="col">
                @Html.DisplayNameForInnerType((ExpertServiceViewModel e)=>e.CommentsCount)
            </th>
            <th scope="col">عملیات</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model.ExpertServices)
        {
            <tr>
                <td scope="row">
                    @(rowCount++)
                </td>
                <td>@item.Service</td>
                <td>@item.CreationDate</td>
                <td>@item.CommentsCount</td>
                <td>
                    <a class="btn btn-info" asp-controller="Expert" asp-action="Comments" asp-route-id="@item.Id">
                        نظرات مشتریان
                    </a>
                    <a id="delete" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal" data-id="@item.Id" data-name="@item.Service">
                        حذف
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>
<!-- delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">حذف @faName</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                آیا از حذف @faName <span id="modalShowFor" class="text-info"></span> اطمینان دارید؟
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">
                    خیر
                </button>
                <a class="btn btn-danger" id="submitDelete">
                    بله
                </a>
            </div>
        </div>
    </div>
</div>

<script>

    $(document).on("click","#delete", function(){
        var id=$(this).data('id');
        var name=$(this).data('name');
        $(".modal-footer #submitDelete").attr("href","Expert/DeleteExpertService/" + id);
        $("#modalShowFor").html(name);
    });
</script>

App.EndPoint.Mvc.UI/Views/Expert/PastWorks.cshtml
@model IEnumerable<PastWorkViewModel>

@{
    ViewData["Title"] = "سابقه کارها";
    int rowCount = 1;
}
<div class="d-flex justify-content-between">
    <h3>سابقه کارها</h3>
</div>
<hr>

<table class="table table-striped table-hover text-center">
    <thead>
        <tr>
            <th scope="col">
                #
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model=>model.Customer)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model=>model.Service)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model=>model.Price)
            </th>
            <th scope="col">
                @Html.DisplayNameFor(model=>model.ComplitionDate)
            </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td scope="row">
                    @(rowCount++)
                </td>
                <td>@item.Customer</td>
                <td>@item.Service</td>
                <td>@item.Price</td>
                <td>@(((DateTime) item.ComplitionDate).ToShamsi())</td>
            </tr>
        }
    </tbody>
</table>